package cmd

import (
	"fmt"
	"os"
	"text/template"

	"github.com/spf13/cobra"
)

func newInitCmd() *cobra.Command {
	var outputPath string
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Generate a starter ditto.yaml from environment or defaults",
		Long: `Write a minimal ditto.yaml to the current directory (or --output path).

If DITTO_SOURCE_URL is set, source fields are pre-populated from it.
Obfuscation rule stubs are included as comments — uncomment and fill them in.

Run this once, then edit the generated file to add obfuscation rules and
adjust the dump schedule. Afterwards, run ditto doctor to verify the setup.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runInit(outputPath)
		},
	}
	cmd.Flags().StringVarP(&outputPath, "output", "o", "ditto.yaml", "Path to write the generated config")
	return cmd
}

type initTemplateData struct {
	SourceURL    string
	Engine       string
	Host         string
	Port         int
	Database     string
	User         string
	DumpPath     string
	DumpSchedule string
	TTL          int
	PortStart    int
	PortEnd      int
}

var initTemplate = template.Must(template.New("ditto.yaml").Parse(`# ditto.yaml — generated by ditto init
# Edit this file, then run: ditto doctor
# Docs: https://github.com/attaradev/ditto

source:
{{- if .SourceURL}}
  url: "{{.SourceURL}}"
{{- else}}
  engine: {{.Engine}}        # postgres or mysql
  host: {{.Host}}
  port: {{.Port}}
  database: {{.Database}}
  user: {{.User}}
  password_secret: "env:DITTO_SOURCE_PASSWORD"  # set DITTO_SOURCE_PASSWORD in your environment
{{- end}}

dump:
  path: "{{.DumpPath}}"
  schedule: "{{.DumpSchedule}}"   # hourly by default; use cron syntax
  stale_threshold: 7200            # warn when dump is older than 2h

copy_ttl_seconds: {{.TTL}}
port_pool_start: {{.PortStart}}
port_pool_end: {{.PortEnd}}

# Uncomment and fill in obfuscation rules to scrub PII during ditto reseed.
# Ditto validates referenced columns before the dump starts.
# During obfuscation, it also hard-errors if a rule updates 0 rows.
# Add warn_only: true to downgrade only that 0-row case to a warning.
#
# obfuscation:
#   rules:
#     - table: users
#       column: email
#       strategy: replace
#       type: email
#     - table: users
#       column: full_name
#       strategy: replace
#       type: name
#     - table: users
#       column: phone
#       strategy: replace
#       type: phone
#     - table: payment_methods
#       column: card_number
#       strategy: mask
#       mask_char: "*"
#       keep_last: 4
#     - table: audit_logs
#       column: ip_address
#       strategy: replace
#       type: ip

# Shared-host mode (for CI teams). Uncomment to enable.
# Requires ditto host to be running. If static_token is set, ditto uses it.
# For production, omit static_token and configure the full OIDC block instead.
#
# server:
#   enabled: true
#   addr: ":8080"
#   advertise_host: "ditto.internal"   # DNS name reachable from CI runners
#   db_bind_host: "0.0.0.0"
#   copy_secret_secret: "env:DITTO_COPY_SECRET"
#   auth:
#     static_token: "env:DITTO_STATIC_TOKEN"   # simple auth; switch to OIDC for production
#   db_tls:
#     cert_file: "/etc/ditto/tls/server.crt"   # required in current shared-host mode
#     key_file: "/etc/ditto/tls/server.key"
#   # For OIDC (recommended in production):
#   # auth:
#   #   issuer: "https://accounts.google.com"
#   #   audience: "ditto-ci"
#   #   jwks_url: "https://www.googleapis.com/oauth2/v3/certs"
`))

func runInit(outputPath string) error {
	if _, err := os.Stat(outputPath); err == nil {
		return fmt.Errorf("%s already exists — remove it first or use --output to write elsewhere", outputPath)
	}

	data := initTemplateData{
		SourceURL:    os.Getenv("DITTO_SOURCE_URL"),
		Engine:       "postgres",
		Host:         "localhost",
		Port:         5432,
		Database:     "myapp",
		User:         "myapp",
		DumpPath:     defaultDumpPath(),
		DumpSchedule: "0 * * * *",
		TTL:          7200,
		PortStart:    5433,
		PortEnd:      5600,
	}

	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("create %s: %w", outputPath, err)
	}
	defer func() { _ = f.Close() }()

	if err := initTemplate.Execute(f, data); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	fmt.Printf("Wrote %s\n", outputPath)
	fmt.Println()
	fmt.Println("Next steps:")
	fmt.Println("  1. Edit ditto.yaml — add your source credentials and obfuscation rules")
	fmt.Println("  2. Run: ditto doctor      — verify everything is set up correctly")
	fmt.Println("  3. Run: ditto reseed      — build the first obfuscated dump")
	fmt.Println("  4. Run: ditto copy run -- <your-migration-command>")
	return nil
}

func defaultDumpPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ".ditto/latest.gz"
	}
	return home + "/.ditto/latest.gz"
}
